name: Build gh-pages
on:  
  push:
    branches:
      - main
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: yarn install
    - run: yarn build

    - name: Deploy
    uses: s0/git-publish-subdir-action@develop
    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: dist
      SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}